nodeapp:
  # This image tag can be automatically updated by invoking the workflow
  # included in this repository 
  image: quay.io/rh_ee_sekumar/gitops-and-actions:sha-baad0b9
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "1"
